# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [ push, pull_request ]

jobs:
    docker:
        runs-on: ubuntu-latest
            steps:
                - name: Checkout
                    uses: actions/checkout@v2
                - name: build
                    uses: addnab/docker-run-action@v1
                    with:
                        image: 'Dockerfile'
                        run: 'build.sh'
